Do not output any HTML if no purchases are recorded
easydigitaldownloads/edd-purchase-gravatars pull request #18
Opened 2021-08-03 15:54 UTC by robincornett

Fixes #10, #14

Proposed changes:
1. Move early return in `gravatars` method and change early returns to an empty string.
2. Remove `extract` from shortcode attributes.
3. Check download for sales and return an empty string for the shortcode if there are none.

2021-08-03 17:47 UTC, LisaCee requested changes
Just a few little nit-picky things for the linter.

I'm also wondering about the Gravatar visibility, and this is slightly different than what's described in issue 10. Is there a way we can see if no buyers have a Gravatar account and if so, not show the h2?  None of my fake customers have a Gravatar account and with Gravatar Visibility checked in the settings, I am getting the heading but  no images. Does that make sense?

2021-08-03 17:47 UTC, LisaCee commented on edd-purchase-gravatars.php
> +			// return if no ID
Will you add a period here to appease the linter?

2021-08-03 17:47 UTC, LisaCee commented on edd-purchase-gravatars.php
> +					return '';
I know it's inherited code, will you add the `{ }` to this function?

2021-08-03 17:47 UTC, LisaCee commented on edd-purchase-gravatars.php
> +		 * Outputs the customer gravatars for a specific download.
Will you add an @param here for $atts?

2021-08-03 17:47 UTC, LisaCee commented on edd-purchase-gravatars.php
> +			// On a singular download, gets the current ID.
Super nit-picky, but should this be `get` instead of `gets`?

2021-08-03 18:13 UTC, robincornett commented
That's a really good call about not putting out the title if there isn't a gravatar, @LisaCee, thanks!

2021-08-03 18:32 UTC, LisaCee approved these changes

2021-08-11 10:04 UTC, ashleyfae commented on edd-purchase-gravatars.php
>  			if ( is_singular( 'download' ) ) {
```suggestion
			if ( is_singular( 'download' ) && empty( $atts['id'] ) ) {
```

I know this isn't new code, but based on the old comment, I feel like this condition should be in there? :thinking:

2021-08-11 10:07 UTC, ashleyfae commented on edd-purchase-gravatars.php
> +			if ( ! $download instanceof EDD_Download || empty( $download->get_sales() ) ) {
Unless we bump our PHP minimum (which I'm not opposed to, but should be done in a separate PR), this needs to be reworked:

```php
empty( $download->get_sales() )
```

Using a method inside `empty()` like that requires PHP 5.5+.

2021-08-11 11:35 UTC, robincornett commented on edd-purchase-gravatars.php
>  			if ( is_singular( 'download' ) ) {
That would be a behavior change--the current code always uses `get_the_ID()` on a singular download, whether or not an ID was passed through. If you're okay with the behavior change, I'll make it--otherwise I would suggest maybe updating the doc block to more clearly explain the behavior on singular downloads.

2021-08-11 11:38 UTC, ashleyfae commented on edd-purchase-gravatars.php
>  			if ( is_singular( 'download' ) ) {
Okay leave it as is for now. We'll come back to it later if we feel like it.

2021-08-11 11:39 UTC, ashleyfae approved these changes

2021-08-11 11:40 UTC, merged